# Generated by Django 3.1.3 on 2021-05-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caritem',
            unique_together={('chave', 'produto')},
        ),
    ]
